name: Release

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  release:
    if: github.event_name != 'workflow_dispatch'
    name: Release
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      id-token: write
    steps:
      - name: Clone repository
        uses: actions/checkout@v4
        with:
          # This fetches the entire Git history so that Changesets can generate changelogs with the correct commits.
          fetch-depth: 0

      - name: Setup
        uses: ./.github/actions/setup

      - name: Build
        run: pnpm build

      - name: Create release pull request or publish to npm
        id: changesets
        uses: changesets/action@v1.4.5
        with:
          title: "chore: version packages"
          commit: "chore: version packages"
          version: pnpm changeset:version
          publish: pnpm changeset:release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  snapshot:
    if: github.event_name == 'workflow_dispatch'
    name: Release snapshot version
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      id-token: write
    steps:
      - name: Clone repository
        uses: actions/checkout@v4

      - name: Setup
        uses: ./.github/actions/setup

      - name: Build
        run: pnpm build

      - name: Create release pull request or publish to npm
        continue-on-error: true
        run: |
          snapshot=$(git branch --show-current | tr -cs '[:alnum:]-' '-' | tr '[:upper:]' '[:lower:]' | sed 's/-$//')
          pnpm changeset version --no-git-tag --snapshot $snapshot
          pnpm changeset publish --no-git-tag --snapshot $snapshot --tag $snapshot
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
