name: Snapshot

on:
  workflow_dispatch:

jobs:
  snapshot:
    name: Release snapshot version
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      id-token: write

    steps:
      - name: Clone repository
        uses: actions/checkout@v4

      - name: Setup
        uses: ./.github/actions/setup

      - name: Build
        run: pnpm build

      - name: Publish Snapshots
        continue-on-error: true
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          snapshot=$(git branch --show-current | tr -cs '[:alnum:]-' '-' | tr '[:upper:]' '[:lower:]' | sed 's/-$//')
          npm config set "//registry.npmjs.org/:_authToken" "$NPM_TOKEN"
          pnpm changeset version --no-git-tag --snapshot $snapshot
          pnpm changeset publish --no-git-tag --snapshot $snapshot --tag $snapshot